[manager]
show_hidden = false
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"

[preview]
wrap = "no"
tab_size = 2
max_width = 1200
max_height = 1800
cache_dir = ""

[opener]
edit = [
  { run = '${EDITOR:-vim} "$@"', block = true, for = "unix" }
]
open = [
  { run = 'xdg-open "$1"', desc = "Open", for = "linux" }
]
reveal = [
  { run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" }
]
