#!/bin/bash
# =============================================================================
# Phase 4 — Dotfiles
# Deploys config files for Hyprland, Waybar, Rofi, Kitty, and Yazi.
# Pulls Waybar theme from elifouts/Dotfiles, then overlays your own overrides.
# Uses symlinks so you can git pull updates later.
# =============================================================================
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../scripts/helpers.sh"

# ── Guards ────────────────────────────────────────────────────────────────────
phase_check 0 "Bootstrap"
phase_check 1 "NVIDIA Drivers"
phase_check 2 "Core Packages"
phase_check 3 "Desktop Environment"

if phase_already_done 4; then
    log_warn "Phase 4 already completed."
    confirm "Re-run anyway (will overwrite configs)?" || exit 0
fi

DOTS_DIR="$SCRIPT_DIR/configs"
CONFIG_HOME="$HOME/.config"

log_step "Phase 4: Dotfiles"
log_info "Config source: $DOTS_DIR"
log_info "Config target: $CONFIG_HOME"
confirm "This will overwrite existing configs. Continue?" || exit 0

# ── Helper: backup then symlink ───────────────────────────────────────────────
link_config() {
    local src="$1"
    local dest="$2"
    if [[ -e "$dest" && ! -L "$dest" ]]; then
        log_warn "Backing up existing: $dest → ${dest}.bak"
        mv "$dest" "${dest}.bak"
    elif [[ -L "$dest" ]]; then
        rm "$dest"
    fi
    ln -s "$src" "$dest"
    log_ok "Linked: $dest → $src"
}

mkdir -p "$CONFIG_HOME"

# ── 1. Kill any running instances to avoid conflicts ─────────────────────────
log_step "Stopping running compositor/bar instances"
pkill waybar    2>/dev/null || true
pkill hyprland  2>/dev/null || true
sleep 1

# ── 2. Pull elifouts Waybar dotfiles ─────────────────────────────────────────
log_step "Fetching elifouts Waybar configs"
ELIFOUTS_DIR="/tmp/elifouts-dotfiles"
rm -rf "$ELIFOUTS_DIR"
git clone --depth=1 https://github.com/elifouts/Dotfiles.git "$ELIFOUTS_DIR"

# Copy elifouts waybar config as our base
ELIFOUTS_WAYBAR="$ELIFOUTS_DIR/.config/waybar"
if [[ -d "$ELIFOUTS_WAYBAR" ]]; then
    cp -r "$ELIFOUTS_WAYBAR/"* "$DOTS_DIR/waybar/"
    log_ok "elifouts Waybar configs copied to $DOTS_DIR/waybar/"
else
    log_warn "Could not find waybar config in elifouts repo. Check the repo structure."
    log_warn "Path checked: $ELIFOUTS_WAYBAR"
    log_info "Listing repo root:"
    ls "$ELIFOUTS_DIR/.config/" 2>/dev/null || ls "$ELIFOUTS_DIR/" || true
fi
rm -rf "$ELIFOUTS_DIR"

# ── 3. Deploy Hyprland config ─────────────────────────────────────────────────
log_step "Deploying Hyprland config"
mkdir -p "$CONFIG_HOME/hypr"
if [[ -d "$DOTS_DIR/hyprland" && "$(ls -A "$DOTS_DIR/hyprland")" ]]; then
    for f in "$DOTS_DIR/hyprland/"*; do
        link_config "$f" "$CONFIG_HOME/hypr/$(basename "$f")"
    done
else
    log_warn "No Hyprland configs in $DOTS_DIR/hyprland — generating minimal config"
    mkdir -p "$DOTS_DIR/hyprland"
    cat > "$DOTS_DIR/hyprland/hyprland.conf" <<'HYPREOF'
# Minimal Hyprland config — customise this
# Generated by arch-setup phase4

# NVIDIA-specific env vars (required for RTX 2070 Super on Wayland)
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1

# Monitor (auto-detect; change 'preferred' to e.g. '1920x1080@144' if needed)
monitor=,preferred,auto,1

# Startup
exec-once = waybar
exec-once = dunst
exec-once = swww-daemon
exec-once = nm-applet --indicator
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Input
input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = yes
    }
}

# General
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(33ccffee)
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}

# Decoration
decoration {
    rounding = 10
    blur {
        enabled = true
        size = 3
        passes = 1
    }
}

# Animations
animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

# Keybindings
$mainMod = SUPER
bind = $mainMod, Q, exec, kitty
bind = $mainMod, C, killactive
bind = $mainMod, M, exit
bind = $mainMod, E, exec, yazi
bind = $mainMod, R, exec, rofi -show drun
bind = $mainMod, P, pseudo
bind = $mainMod, J, togglesplit
bind = $mainMod, left,  movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up,    movefocus, u
bind = $mainMod, down,  movefocus, d
bind = $mainMod SHIFT, left,  movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up,    movewindow, u
bind = $mainMod SHIFT, down,  movewindow, d

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# Screenshots
bind = , Print, exec, grim -g "$(slurp)" - | wl-copy

# Window rules
windowrule = float, ^(pavucontrol)$
windowrule = float, ^(blueman-manager)$
HYPREOF
    link_config "$DOTS_DIR/hyprland/hyprland.conf" "$CONFIG_HOME/hypr/hyprland.conf"
fi

# ── 4. Deploy Waybar config ───────────────────────────────────────────────────
log_step "Deploying Waybar config"
mkdir -p "$CONFIG_HOME/waybar"
if [[ -d "$DOTS_DIR/waybar" && "$(ls -A "$DOTS_DIR/waybar")" ]]; then
    # Remove existing waybar config dir if not a symlink
    [[ -d "$CONFIG_HOME/waybar" && ! -L "$CONFIG_HOME/waybar" ]] && rm -rf "$CONFIG_HOME/waybar"
    link_config "$DOTS_DIR/waybar" "$CONFIG_HOME/waybar"
else
    log_warn "No Waybar configs found in $DOTS_DIR/waybar"
fi

# Validate waybar config JSON
if command -v waybar &>/dev/null; then
    if waybar --config "$CONFIG_HOME/waybar/config" --log-level error --check 2>/dev/null; then
        log_ok "Waybar config validates OK."
    else
        log_warn "Waybar config validation failed. Check $CONFIG_HOME/waybar/config for errors."
    fi
fi

# ── 5. Deploy Rofi config ─────────────────────────────────────────────────────
log_step "Deploying Rofi config"
mkdir -p "$CONFIG_HOME/rofi"
if [[ -d "$DOTS_DIR/rofi" && "$(ls -A "$DOTS_DIR/rofi")" ]]; then
    for f in "$DOTS_DIR/rofi/"*; do
        link_config "$f" "$CONFIG_HOME/rofi/$(basename "$f")"
    done
else
    log_warn "No Rofi configs found — creating default Wayland config"
    mkdir -p "$DOTS_DIR/rofi"
    cat > "$DOTS_DIR/rofi/config.rasi" <<'ROFIEOF'
configuration {
    modi: "drun,run,window";
    font: "JetBrainsMono Nerd Font 12";
    show-icons: true;
    terminal: "kitty";
    drun-display-format: "{name}";
    location: 0;
    disable-history: false;
    hide-scrollbar: true;
    display-drun: "   Apps ";
    display-run: "   Run ";
    display-window: " 﩯  Window";
    sidebar-mode: true;
}

@theme "~/.config/rofi/theme.rasi"
ROFIEOF
    # Default theme (works with rofi-wayland)
    cat > "$DOTS_DIR/rofi/theme.rasi" <<'THEMEEOF'
* {
    background-color:   #1e1e2eFF;
    border-color:       #cba6f7FF;
    text-color:         #cdd6f4FF;
    font:               "JetBrainsMono Nerd Font 13";
}
window {
    width: 600px;
    border: 2px;
    border-radius: 12px;
    padding: 20px;
}
mainbox {
    border:  0;
    padding: 0;
}
inputbar {
    children:   [prompt, entry];
    background-color: #313244FF;
    border-radius: 8px;
    padding: 8px;
    margin: 0px 0px 10px 0px;
}
prompt {
    color: #cba6f7FF;
    padding: 0px 8px 0px 0px;
}
entry {
    color: #cdd6f4FF;
}
listview {
    lines: 8;
    columns: 1;
    spacing: 4px;
}
element {
    border-radius: 6px;
    padding: 8px;
}
element selected {
    background-color: #cba6f7FF;
    text-color: #1e1e2eFF;
}
THEMEEOF
    link_config "$DOTS_DIR/rofi/config.rasi" "$CONFIG_HOME/rofi/config.rasi"
    link_config "$DOTS_DIR/rofi/theme.rasi"  "$CONFIG_HOME/rofi/theme.rasi"
fi

# ── 6. Deploy Kitty config ────────────────────────────────────────────────────
log_step "Deploying Kitty config"
mkdir -p "$CONFIG_HOME/kitty"
if [[ -d "$DOTS_DIR/kitty" && "$(ls -A "$DOTS_DIR/kitty")" ]]; then
    for f in "$DOTS_DIR/kitty/"*; do
        link_config "$f" "$CONFIG_HOME/kitty/$(basename "$f")"
    done
else
    log_warn "No Kitty config found — creating default"
    mkdir -p "$DOTS_DIR/kitty"
    cat > "$DOTS_DIR/kitty/kitty.conf" <<'KITTYEOF'
# Kitty config
font_family      JetBrainsMono Nerd Font
font_size        13.0
cursor_shape     beam
scrollback_lines 10000
enable_audio_bell no
window_padding_width 10
background_opacity 0.95
# Catppuccin Mocha theme
include ./mocha.conf
KITTYEOF
    # Catppuccin Mocha colour scheme
    cat > "$DOTS_DIR/kitty/mocha.conf" <<'MOCHA'
foreground              #CDD6F4
background              #1E1E2E
selection_foreground    #1E1E2E
selection_background    #F5E0DC
cursor                  #F5E0DC
cursor_text_color       #1E1E2E
url_color               #F5E0DC
color0  #45475A
color1  #F38BA8
color2  #A6E3A1
color3  #F9E2AF
color4  #89B4FA
color5  #F5C2E7
color6  #94E2D5
color7  #BAC2DE
color8  #585B70
color9  #F38BA8
color10 #A6E3A1
color11 #F9E2AF
color12 #89B4FA
color13 #F5C2E7
color14 #94E2D5
color15 #A6ADC8
MOCHA
    link_config "$DOTS_DIR/kitty/kitty.conf" "$CONFIG_HOME/kitty/kitty.conf"
    link_config "$DOTS_DIR/kitty/mocha.conf"  "$CONFIG_HOME/kitty/mocha.conf"
fi

# ── 7. Deploy Yazi config ─────────────────────────────────────────────────────
log_step "Deploying Yazi config"
mkdir -p "$CONFIG_HOME/yazi"
if [[ -d "$DOTS_DIR/yazi" && "$(ls -A "$DOTS_DIR/yazi")" ]]; then
    for f in "$DOTS_DIR/yazi/"*; do
        link_config "$f" "$CONFIG_HOME/yazi/$(basename "$f")"
    done
else
    log_warn "No Yazi config found — creating default yazi.toml"
    mkdir -p "$DOTS_DIR/yazi"
    cat > "$DOTS_DIR/yazi/yazi.toml" <<'YAZIEOF'
[manager]
ratio          = [1, 4, 3]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
show_hidden    = false
show_symlink   = true
scrolloff      = 5

[preview]
image_filter = "lanczos3"
image_quality = 75
tab_size      = 2
max_width     = 600
max_height    = 900

[log]
enabled = false
YAZIEOF
    link_config "$DOTS_DIR/yazi/yazi.toml" "$CONFIG_HOME/yazi/yazi.toml"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
phase_done 4
echo -e "\n${GREEN}${BOLD}Phase 4 complete.${RESET}"
echo -e "Next: ${BOLD}phase5-tests/pre-reboot.sh${RESET}"
